<?php

/**
 * @file
 * Primary module hooks for mp_flickr module.
 */

/**
 * Implements hook_theme().
 */
function mp_flickr_theme($existing, $type, $theme, $path) {
  return [

    'photo' => [
      'variables' => [
        'photo_id' => NULL,
        'photo' => NULL,
      ],
    ],

    'gallery' => [
      'variables' => [
        'gallery_id' => NULL,
        'gallery' => NULL,
      ],
    ],

    'gallery_slick' => [
      'variables' => [
        'gallery_id' => NULL,
        'gallery' => NULL,
      ],
    ],

    'photo_slick' => [
      'variables' => [
        'photo_id' => NULL,
        'photo' => NULL,
      ],
    ],

  ];
}

/**
 * Implements hook_page_attachments().
 */
function mp_flickr_page_attachments(&$variables) {
  $variables['#attached']['library'][] = 'mp_flickr/slick';
}
